name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine toml
        pip install -r requirements-dev.txt
        
    - name: Run tests
      run: |
        pytest
        
    - name: Extract version from tag
      id: get_version
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Verify version in pyproject.toml
      run: |
        package_version=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
        tag_version=${{ steps.get_version.outputs.version }}
        if [ "$package_version" != "$tag_version" ]; then
          echo "::error::Version mismatch: Tag is v$tag_version but pyproject.toml version is $package_version"
          exit 1
        fi
        
    - name: Build package
      run: |
        python -m build
        
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false
        body: |
          # DataScoop ${{ steps.get_version.outputs.version }}
          
          ## Changes
          
          <!-- Release notes go here -->
          
        files: |
          dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
